In [123]:
import tensorflow as tf

import numpy as np

import pandas as pd

from tensorflow import keras

from sklearn.model_selection import train_test_split

In [124]:
data = pd.read_csv("C:/Users/Abhi/Downloads/insurance_data (1).csv")

In [125]:
data.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [126]:
X_train ,X_test , y_train , y_test = train_test_split(data[['age' , 'affordibility']], data.bought_insurance , test_size = 0.2,random_state = 1)

In [127]:
X_train.head()

age  affordibility
22   40              1
10   18              1
21   26              0
4    46              1
2    47              1

In [128]:
y_train.head()

22    1
10    0
21    0
4     1
2     1
Name: bought_insurance, dtype: int64

In [129]:
X_train.shape

(22, 2)

In [130]:
X_test.shape

(6, 2)

In [131]:
y_test.shape

(6,)

In [132]:
x_train_scaled = X_train.copy()

x_train_scaled['age'] = X_train['age']/100

x_test_scaled = X_test.copy()

x_test_scaled['age'] = X_test['age']/100

x_train_scaled.shape

(22, 2)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x_train_scaled, y_train, epochs=4000)

Epoch 1/4000


C:\Users\Abhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7068
Epoch 2/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7064
Epoch 3/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7060
Epoch 4/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 5/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7053
Epoch 6/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7049
Epoch 7/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 8/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7042
Epoch 9/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7038
Epoch 10/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 11/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7031
Epoch 12/4000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss:

In [143]:
model.evaluate(x_test_scaled , y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.4308


[0.43077221512794495, 1.0]

In [144]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.7177657 ],
       [0.7827902 ],
       [0.3867547 ],
       [0.41817945],
       [0.7088554 ],
       [0.4692391 ]], dtype=float32)

In [145]:
y_test

24    1
17    1
19    0
20    0
14    1
3     0
Name: bought_insurance, dtype: int64

In [146]:
coef , intercept = model.get_weights()

In [147]:
coef

array([[4.357438 ],
       [1.1437536]], dtype=float32)

In [148]:
intercept

array([-2.389067], dtype=float32)

In [149]:
def sigmoid_np(x):

    return 1 / (1+ np.exp(-x))

In [150]:
def log_loss(y_true , y_predicted):

    epsilon = 1e-15
    y_predicted = [max(i , epsilon) for i in y_predicted]
    
    y_predicted = [min(i , 1- epsilon) for i in y_predicted]

    y_predicted = np.array(y_predicted)
    return -1* np.mean(y_true * np.log(y_predicted) + (1 - y_true) * np.log( 1 - y_predicted))
    

In [154]:
def gradient_descent(age , affordability ,y_true , epochs ):

    w1 = w2 = 1
    
    bias = 0 

    n =len(age)

    learning_rate = 0.5

    for i in range(epochs):

        weighted_sum = (age * w1) + (affordability * w2) + bias
    
        y_predicted = sigmoid_np(weighted_sum)
        
        loss = log_loss(y_true , y_predicted)
        
        w1_d = 1/n * np.dot(np.transpose(age) , (y_predicted - y_true) )
            
        w2_d = 1/n * np.dot(np.transpose(affordability) ,  (y_predicted - y_true) )

        bias_d = np.mean(y_predicted - y_true)

        w1 -= learning_rate * w1_d
        
        w2 -= learning_rate * w2_d
        
        bias -= learning_rate * bias_d
        
        print(f"Epoch : {i} , w1 : {w1} , w2 : {w2} , loss : {loss} , bias : {bias}")

        if loss <=  0.4719:

           break

        
    return w1,w2,bias


gradient_descent(x_train_scaled['age'] ,x_train_scaled['affordibility'] , y_train , epochs = 5000)

Epoch : 0 , w1 : 0.9776620922402962 , w2 : 0.9480790207203986 , loss : 0.7067871004847728 , bias : -0.11226706670803967
Epoch : 1 , w1 : 0.9609125476331305 , w2 : 0.9052188491853423 , loss : 0.6773703034021942 , bias : -0.21016179153380088
Epoch : 2 , w1 : 0.9492783314404287 , w2 : 0.8707929230331629 , loss : 0.6556794409382555 , bias : -0.2949739823330707
Epoch : 3 , w1 : 0.9421933435116123 , w2 : 0.8439510422734104 , loss : 0.6399398037987551 , bias : -0.36819527558430154
Epoch : 4 , w1 : 0.9390600941197916 , w2 : 0.8237381332741572 , loss : 0.6286123161559022 , bias : -0.4313687285337374
Epoch : 5 , w1 : 0.9392964192684764 , w2 : 0.8091892305731584 , loss : 0.6204572707469723 , bias : -0.48597817221168843
Epoch : 6 , w1 : 0.9423650744066836 , w2 : 0.7993932021215371 , loss : 0.614530223245117 , bias : -0.5333804796544527
Epoch : 7 , w1 : 0.9477887313466666 , w2 : 0.7935282311962205 , loss : 0.6101410500908765 , bias : -0.5747733000515152
Epoch : 8 , w1 : 0.9551545435874927 , w2 : 0.

(4.314310750116437, 1.2721413427920016, -2.493214971431264)

In [ ]:
# Check out the Intercept(-2.389067) and Coefficients (4.357438 ,1.1437536) calculated by Tensor FLow 
# Coefficients (4.314310750116437 , 1.2721413427920016) and Intercept (-2.493214971431264) calculated using clean Python are almost similar .